### ISSUE TITLE
The `watch` tasks seems to be running in the background even after the app is closed

### ISSUE THREAD

**Issue by floydpink** [szwacz/electron-boilerplate#12] opened 2015-06-22 16:44 UTC
Try these steps to reproduce this issue:

1. Clone the repo
2. Run `npm install` at the root of the repo
3. Run `npm start` to start the electron app
4. Close the app - the terminal window will also show the prompt (giving the indication that all the background tasks are terminated)
5. Make a trivial whitespace change to `/app/hello_world/hello_universe.js` and save
6. Notice that the terminal window will start the `transpile-watch` task

```plain
$ [12:37:26] Starting 'transpile-watch'...
[12:37:26] Finished 'transpile-watch' after 47 ms
```

Testing this with the [latest commit as of now](https://github.com/szwacz/electron-boilerplate/commit/db6a4f7201533fa8003e193a0ff6ab4670f8f875) on a Mac, with node and npm versions as below:

```plain
$ node -v
v0.12.4

$ npm -v
2.11.3
```

**Comment by carlosperate** [comment] 2015-06-22 16:47
I can confirm the same under Windows 8.1.

**Comment by szwacz** [comment] 2015-06-22 17:47
Ok, so it wasn't only my machine :) It happened randomly and rarely so I assumed this is some funkiness on my system.
Added explicit kill to on main process exit (https://github.com/szwacz/electron-boilerplate/commit/9aefea226b20107794eeb17c9fe09f12705f227c). How about now?

**Comment by floydpink** [comment] 2015-06-22 20:40
:+1:  - that seems to have fixed it

**Comment by carlosperate** [comment] 2015-06-22 23:43
Sorry I can't say the same, still experiencing the same `transpile-watch` issue.

**Comment by szwacz** [comment] 2015-06-23 18:19
@carlosperate are you sure you've killed all zombie processes of gulp watch started previously before trying this?

**Comment by carlosperate** [comment] 2015-06-23 20:13
Yeah, I just tried it on a fresh restart with a new clone of master and still the same.
I should also add that when the I close the application I also get the following errors:

```
[1988:0623/205934:ERROR:ipc_channel_win.cc(414)] pipe error: 232
[1988:0623/205934:ERROR:ipc_channel_win.cc(138)] pipe error: 109
```

I've experience both these issues from the beginning (a bit longer than a week ago is when I first used it), and it has not been intermittent. 

Testing on Windows 8.1 64 bit, running node 0.12.4 32 bit, and npm 2.10.1.

**Comment by szwacz** [comment] 2015-06-24 19:46
Hah, it appears killing child process on Windows is harder than one might think. Could you try with https://github.com/szwacz/electron-boilerplate/commit/125b45853fb88227f7a490f69c1e58979e70a3f2 ?

**Comment by carlosperate** [comment] 2015-06-26 00:23
Yeah, that did the trick.
Although now I am only getting one pipe error when the window is closed, should I open a different issue for that?
```
```

**Comment by szwacz** [comment] 2015-06-26 05:29
Great!

I have no idea what this pipe error is, and it's generated from low level electron stuff (not a JS error), so I don't know if there is something I can do with it.

**Comment by carlosperate** [comment] 2015-06-26 16:33
Have you seen such pip error on your Windows testing? If so, could you raise a bug report in the appropriate channel? I have no idea how the software stack is organised, simple google search about it usually points to chromium build errors.

**Comment by pkunze** [comment] 2016-02-23 07:54
I think this issue should be reopened. I am able to reproduce it with a fresh install of the boilerplate. I noticed it because after I close the electron-window the console does return and prints out right afterwards. 

```bash
[08:25:08] Starting gulpfile /path/to/gulpfile.js
[08:25:08] Starting 'watch'...
```

again (after it already retorned to the working directory. See Screenshot below):

![gulp-watch-after-quit](https://cloud.githubusercontent.com/assets/1416798/13244739/e01afa54-da08-11e5-9aee-bdd28fbaa827.PNG)

After i noticed this, I tried to reproduce the issue using the steps provided by @floydpink wich works sometimes. 

Also, the build takes longer everytime I comile again. Also, after using `npm start` a few times, the cpu load is at a steady pace of 100% on every (Windows-)maschine I try it with. This can be solved temporarely by closing the used cmd window and using a new one, but the process slowly starts again.

Am I doing something wrong?

**Comment by black-snow** [comment] 2016-02-23 10:57
Nah, it's the same here, too. I just got used to it. Gotta hit `crtl + c` a couple times when I wanna stop everything.

**Comment by carlosperate** [comment] 2016-02-23 11:49
I've experienced the same.

**Comment by szwacz** [comment] 2016-02-23 19:30
Why noone told then? :)
I don't know why killing child processes on window is so difficult. Will into it in near future. All helping hands are welcome!

**Comment by black-snow** [comment] 2016-02-23 22:10
While it's annoying you also get used to it pretty fast :D

I recently had quite the same issue in one of my projects. I didn't find any satisfying solution. Tried pretty much any of these answers: http://stackoverflow.com/questions/23706055/why-can-i-not-kill-my-child-process-in-nodejs-on-windows
See also https://www.exratione.com/2013/05/die-child-process-die/ and https://github.com/nodejs/node-v0.x-archive/issues/1811

Maybe this will do the trick: https://www.npmjs.com/package/tree-kill

**Comment by pkunze** [comment] 2016-02-24 07:18
I think i've localized the possible issue: 

it's in `tasks/start.js`:

I added some console-logs to make my point clear. see the attached console-screenshot* for an example...

runGulpWatch respawns the process when watch is closed:

```javascript
var runGulpWatch = function () {
    console.log('[runGulpWatch] Im getting spawned now')

    watch = childProcess.spawn(utils.spawnablePath(gulpPath), [
        'watch',
        '--env=' + utils.getEnvName(),
        '--color'
    ], {
        stdio: 'inherit'
    });

    watch.on('close', function (code) {
        // Gulp watch exits when error occured during build.
        // Just respawn it then.
        console.log('[runGulpWatch] Im restarting my self now')
        runGulpWatch();
    });
};
```

which is also triggered when the app exits by doing
```javascript 
var runApp = function () {
    var app = childProcess.spawn(electron, ['./build'], {
        stdio: 'inherit'
    });

    app.on('close', function (code) {
        // User closed the app. Kill the host process.
        console.log('[runApp] Im killing gulps watch task right now ;)')
        kill(watch.pid, 'SIGKILL', function () {            
            process.exit();
        });
    });
};
```
which seems to respawn the watch task (at least on windows):

![gulp-watch-after-quit-2](https://cloud.githubusercontent.com/assets/1416798/13278078/cf2fb840-dacd-11e5-8a8f-30f58d6e4b60.PNG)

So from my point of view, the automatic respawn of `watch` causes the problem.

**Comment by JimmyBoh** [comment] 2016-02-26 06:45
I've submitted a [PR](https://github.com/szwacz/electron-boilerplate/pull/123) with a simple fix for the auto-restart when closing. It just sets a flag when it should not restart the watch task. The only question left is what happens when you forcefully stop the initial node process (hit `Ctrl + C` twice). Does it clean up the child processes correctly?

**Comment by carlosperate** [comment] 2016-02-26 11:58
If I remember correctly `"tree-kill` was added exclusively to try to fix this issue, so if this PR offers a solution that. in addition, allows us to remove a dependency it sounds good to me.

**Comment by szwacz** [comment] 2016-02-26 20:53
Yes `tree-kill` was added specially for this purpose.
Actuall removing `tree-kill` completely for me solved the issue. Can you try that as well?
Maybe newer version of node just works and no workaround is necessery.

**Comment by JimmyBoh** [comment] 2016-02-26 21:19
I will try it later today or tomorrow and definitely let you know!

**Comment by JimmyBoh** [comment] 2016-02-29 17:18
So after removing `tree-kill` it seems to be doing better, but still not that great. One thing I did try was removing the reference to the `node_modules` folder from [line 19](https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build.js#L19) and then re-added it as necessary ([line 38](https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build.js#L38)). I need to keep testing it, but maybe the watch task was just having a hard time keeping track of all the dependencies.

**Comment by szwacz** [comment] 2016-02-29 20:31
@JimmyBoh if you think big count of files in `node_modules` might be a factor then you can just comment the watch task for `'copy-watch'` and see how it goes then.

**Comment by szwacz** [comment] 2016-03-19 19:00
Watch task has been refactored. Now using gulp-plumber and gulp-watch without creating child processes. Hope this solves all issues with watch task. Please give it a try.

**Closed by szwacz** 2016-03-19 19:00 UTC
